cleanup trailing whitespace and use spaces for indentation

diff --git a/check_ipmi_sensor b/check_ipmi_sensor
--- a/check_ipmi_sensor
+++ b/check_ipmi_sensor
@@ -8,12 +8,12 @@
 # the terms of the GNU General Public License as published by the Free Software
 # Foundation; either version 3 of the License, or (at your option) any later
 # version.
-# 
+#
 # This program is distributed in the hope that it will be useful, but WITHOUT
 # ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 # FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 # details.
-# 
+#
 # You should have received a copy of the GNU General Public License along with
 # this program; if not, see <http://www.gnu.org/licenses/>.
 #
@@ -134,38 +134,38 @@ else missing_command_text=" ipmimonitoring command not found."
 fi
 
 ################################################################################
-# read parameters 
+# read parameters
 # * uses getopts, see http://tldp.org/LDP/abs/html/internal.html#GETOPTSX
 while getopts "H:f:U:P:L:O:bT:v:x:o:hV?" option
 do
-	case $option in
-		H)	IPMI_HOST=$OPTARG;;
-		f)	IPMI_CONFIG_FILE=$OPTARG;;
-		U)	IPMI_USER=$OPTARG;;
-		P)	IPMI_PASSWORD=$OPTARG;;
-		L)	IPMI_PRIVILEGE_LEVEL=$OPTARG;;
-		O)	FREEIPMI_OPTIONS=$OPTARG;;
-		b)	FREEIPMI_BACKWARD_COMPATIBILITY=1;;
-		T)	IPMI_SENSOR_TYPE=$OPTARG;;
-		v)	VERBOSITY=$OPTARG;;
-		x)	if [ -z "$IPMI_XLIST" ]; then
-				IPMI_XLIST="$OPTARG"
-			else
-				IPMI_XLIST="${IPMI_XLIST};$OPTARG"
-			fi
-			;;
-		o)	IPMI_OUTFORMAT=$OPTARG;;
-		h)	echo "$version_text"
-			echo
-			echo "$usage_text"
-			echo
-			echo "$help_text"
-		  	exit 0;;
-		V)	echo "$version_text"
-		  	exit 0;;
-		\?)	echo "$usage_text"
-		  	exit 3;;
-	esac
+  case $option in
+    H)  IPMI_HOST=$OPTARG;;
+    f)  IPMI_CONFIG_FILE=$OPTARG;;
+    U)  IPMI_USER=$OPTARG;;
+    P)  IPMI_PASSWORD=$OPTARG;;
+    L)  IPMI_PRIVILEGE_LEVEL=$OPTARG;;
+    O)  FREEIPMI_OPTIONS=$OPTARG;;
+    b)  FREEIPMI_BACKWARD_COMPATIBILITY=1;;
+    T)  IPMI_SENSOR_TYPE=$OPTARG;;
+    v)  VERBOSITY=$OPTARG;;
+    x)  if [ -z "$IPMI_XLIST" ]; then
+        IPMI_XLIST="$OPTARG"
+      else
+        IPMI_XLIST="${IPMI_XLIST};$OPTARG"
+      fi
+      ;;
+    o)  IPMI_OUTFORMAT=$OPTARG;;
+    h)  echo "$version_text"
+      echo
+      echo "$usage_text"
+      echo
+      echo "$help_text"
+        exit 0;;
+    V)  echo "$version_text"
+        exit 0;;
+    \?) echo "$usage_text"
+        exit 3;;
+  esac
 done
 
 ###############################################################################
@@ -186,32 +186,32 @@ fi
 # verify if all mandatory parameters are set and initialize various variables
 if [ -z "$IPMI_HOST" ]; then abort_text="$abort_text -H <hostname>"
 else
-	if [ "$IPMI_HOST" == "localhost" ]; then
-		BASECOMMAND="sudo $IPMICOMMAND"
-	else
-		if [ -n "$IPMI_CONFIG_FILE" ]; then
-			BASECOMMAND="$IPMICOMMAND -h $IPMI_HOST --config-file $IPMI_CONFIG_FILE"
-		elif [ -n "$IPMI_USER" -a -n "$IPMI_PASSWORD" -a -n "$IPMI_PRIVILEGE_LEVEL" ]; then
-			BASECOMMAND="$IPMICOMMAND -h $IPMI_HOST -u $IPMI_USER -p $IPMI_PASSWORD -l $IPMI_PRIVILEGE_LEVEL"
-		else 
-			abort_text="$abort_text -f <FreeIPMI config file> or -U <username> -P <password> -L <privilege level>"; fi
-	fi
+  if [ "$IPMI_HOST" == "localhost" ]; then
+    BASECOMMAND="sudo $IPMICOMMAND"
+  else
+    if [ -n "$IPMI_CONFIG_FILE" ]; then
+      BASECOMMAND="$IPMICOMMAND -h $IPMI_HOST --config-file $IPMI_CONFIG_FILE"
+    elif [ -n "$IPMI_USER" -a -n "$IPMI_PASSWORD" -a -n "$IPMI_PRIVILEGE_LEVEL" ]; then
+      BASECOMMAND="$IPMICOMMAND -h $IPMI_HOST -u $IPMI_USER -p $IPMI_PASSWORD -l $IPMI_PRIVILEGE_LEVEL"
+    else
+      abort_text="$abort_text -f <FreeIPMI config file> or -U <username> -P <password> -L <privilege level>"; fi
+  fi
 fi
 if [ -n "$missing_command_text" ]; then
-	echo "Error:$missing_command_text"
-	exit 3
+  echo "Error:$missing_command_text"
+  exit 3
 fi
 if [ -n "$abort_text" ]; then
-	echo "Error:$abort_text missing."
-	echo "$usage_text"
-	exit 3
+  echo "Error:$abort_text missing."
+  echo "$usage_text"
+  exit 3
 fi
 if [ -n "$IPMI_SENSOR_TYPE" ]; then BASECOMMAND="$BASECOMMAND -g $IPMI_SENSOR_TYPE"; fi
 if [ -n "$FREEIPMI_OPTIONS" ]; then BASECOMMAND="$BASECOMMAND $FREEIPMI_OPTIONS"; fi
 if [ -n "$FREEIPMI_BACKWARD_COMPATIBILITY" ]; then
-	GET_STATUS="$BASECOMMAND"
+  GET_STATUS="$BASECOMMAND"
 else
-	GET_STATUS="$BASECOMMAND --quiet-cache --sdr-cache-recreate"
+  GET_STATUS="$BASECOMMAND --quiet-cache --sdr-cache-recreate"
 fi
 
 if [ -z "$IPMI_XLIST" ];then
@@ -233,47 +233,47 @@ returncode=$?
 # print debug output when verbosity is set to 3 (-v 3)
 if [ "$VERBOSITY" = "3" ]
 then
-	echo "------------- begin of debug output (-v 3 is set): ------------"
-	echo "  script was executed with the following parameters:"
-	echo "    $0 $@"
-	echo "  check_ipmi_sensor version:"
-	echo "    $version"
-	echo "  ipmimonitoring version:"
-	echo "    $ipmicommandversion"
-	echo "  ipmimonitoring was executed with the following parameters:"
-	echo "    $GET_STATUS"
-	echo "  ipmimonitoring return code: $returncode"
-	echo "  output of ipmimonitoring:"
-	echo "$ipmioutput"
+  echo "------------- begin of debug output (-v 3 is set): ------------"
+  echo "  script was executed with the following parameters:"
+  echo "    $0 $@"
+  echo "  check_ipmi_sensor version:"
+  echo "    $version"
+  echo "  ipmimonitoring version:"
+  echo "    $ipmicommandversion"
+  echo "  ipmimonitoring was executed with the following parameters:"
+  echo "    $GET_STATUS"
+  echo "  ipmimonitoring return code: $returncode"
+  echo "  output of ipmimonitoring:"
+  echo "$ipmioutput"
   echo "  Excluded sensor list: $IPMI_XLIST"
-	echo "--------------------- end of debug output ---------------------"
+  echo "--------------------- end of debug output ---------------------"
 fi
 
 ################################################################################
 # generate main output
 if [ $returncode != 0 ]
 then
-	echo "$ipmioutput"
-	echo "-> Execution of ipmimonitoring failed with return code $returncode."
-	echo "-> ipmimonitoring was executed with the following parameters:"
+  echo "$ipmioutput"
+  echo "-> Execution of ipmimonitoring failed with return code $returncode."
+  echo "-> ipmimonitoring was executed with the following parameters:"
         echo "   $GET_STATUS"
-	exit 3
+  exit 3
 else
-	if [ -n "$IPMI_SENSOR_TYPE" ]; then
-		echo -n "Sensor Type '$IPMI_SENSOR_TYPE' Status: ";
-	else
-		echo -n "IPMI Status: ";
+  if [ -n "$IPMI_SENSOR_TYPE" ]; then
+    echo -n "Sensor Type '$IPMI_SENSOR_TYPE' Status: ";
+  else
+    echo -n "IPMI Status: ";
         fi
-	echo "$ipmioutput" | gawk -v verbosity=$VERBOSITY -v xlist="$IPMI_XLIST" -v outformat="$IPMI_OUTFORMAT" -F '|' '
+  echo "$ipmioutput" | gawk -v verbosity=$VERBOSITY -v xlist="$IPMI_XLIST" -v outformat="$IPMI_OUTFORMAT" -F '|' '
 ################################################################################
 # * BEGIN rule is executed once only, before the first input record is read
 #   see http://www.gnu.org/software/gawk/manual/html_node/Using-BEGIN_002fEND.html
 # * we initialize variables here
 BEGIN {
-	EXIT=0
-	number_of_numerical_records=0
-	w_sensors=""
-	split(xlist,xl_array,";")
+  EXIT=0
+  number_of_numerical_records=0
+  w_sensors=""
+  split(xlist,xl_array,";")
 }
 
 ################################################################################
@@ -281,7 +281,7 @@ BEGIN {
 #   output of ipmimonitoring
 #   see http://www.gnu.org/software/gawk/manual/html_node/Regexp-Usage.html
 # * we fill the following arrays with data here:
-#   - arrays containing all sensors:  
+#   - arrays containing all sensors:
 #     - sensor_id[] .......... contains the id of the sensor, e.g. "1"
 #     - sensor_name[] ........ contains the name of the sensor, e.g. "Fan 1"
 #     - sensor_status[] ...... contains the status of the sensor, e.g. "Nominal"
@@ -291,64 +291,64 @@ BEGIN {
 #     - n_record_name[] ...... contains the name of the sensor, e.g. "Fan 1"
 #     - n_record_value[] ..... contains the numerical reading, e.g. "5719.000"
 $4 !~ /Monitoring Status/ {
-	########################################################################
-	# Remove extra spaces
-	gsub(/ +$/,"",$1)
-	gsub(/^ +/,"",$2)
-	gsub(/ +$/,"",$2)
-	gsub(/^ +/,"",$4)
-	gsub(/ +$/,"",$4)
-	gsub(/^ +/,"",$5)
-	gsub(/ +$/,"",$5)
-	gsub(/^ +/,"",$6)
-	gsub(/ +$/,"",$6)
-	# Substitute whitespaces with underscores in sensor_name for ZENOSS
-	if (outformat == "zenoss") gsub(/[[:space:]]/,"_",$2)
+  ########################################################################
+  # Remove extra spaces
+  gsub(/ +$/,"",$1)
+  gsub(/^ +/,"",$2)
+  gsub(/ +$/,"",$2)
+  gsub(/^ +/,"",$4)
+  gsub(/ +$/,"",$4)
+  gsub(/^ +/,"",$5)
+  gsub(/ +$/,"",$5)
+  gsub(/^ +/,"",$6)
+  gsub(/ +$/,"",$6)
+  # Substitute whitespaces with underscores in sensor_name for ZENOSS
+  if (outformat == "zenoss") gsub(/[[:space:]]/,"_",$2)
 
-	sensor_id[NR]=$1
-	sensor_name[NR]=$2
-	# sensor_type[NR]=$3 (currently not used)
-	sensor_status[NR]=$4
-	sensor_units[NR]=$5
-	sensor_reading[NR]=$6
+  sensor_id[NR]=$1
+  sensor_name[NR]=$2
+  # sensor_type[NR]=$3 (currently not used)
+  sensor_status[NR]=$4
+  sensor_units[NR]=$5
+  sensor_reading[NR]=$6
 
-	########################################################################
-	# Omit this sensor if the sensor is included in the list of sensors to 
-	# exclude
-	for (ind in xl_array)
-	{
- 		if (sensor_id[NR] == xl_array[ind]) next 
-	}
-	########################################################################
-	# * set EXIT variable to 1 if a sensor is not "ok" or "ns"
-	# * also build contents of w_sensors variable (sensors with status not
-	#   ok) in this case
-	if (sensor_status[NR] != "Nominal")
-	{
-		if (EXIT < 1) EXIT=1
-		if (EXIT < 2 && sensor_status[NR] != "Warning" ) EXIT=2 
-		if (verbosity>0)
-		{
-			if (w_sensors == "")
-				w_sensors=sensor_name[NR]" = "sensor_status[NR]" ("sensor_reading[NR]")"
-			else
-				w_sensors=w_sensors", "sensor_name[NR]" = "sensor_status[NR]" ("sensor_reading[NR]")"
-		}
-		else
-		{
-			if (w_sensors == "")
-				w_sensors=sensor_name[NR]" = "sensor_status[NR]
-			else
-				w_sensors=w_sensors", "sensor_name[NR]" = "sensor_status[NR]
-		}
-	}
+  ########################################################################
+  # Omit this sensor if the sensor is included in the list of sensors to
+  # exclude
+  for (ind in xl_array)
+  {
+    if (sensor_id[NR] == xl_array[ind]) next
+  }
+  ########################################################################
+  # * set EXIT variable to 1 if a sensor is not "ok" or "ns"
+  # * also build contents of w_sensors variable (sensors with status not
+  #   ok) in this case
+  if (sensor_status[NR] != "Nominal")
+  {
+    if (EXIT < 1) EXIT=1
+    if (EXIT < 2 && sensor_status[NR] != "Warning" ) EXIT=2
+    if (verbosity>0)
+    {
+      if (w_sensors == "")
+        w_sensors=sensor_name[NR]" = "sensor_status[NR]" ("sensor_reading[NR]")"
+      else
+        w_sensors=w_sensors", "sensor_name[NR]" = "sensor_status[NR]" ("sensor_reading[NR]")"
+    }
+    else
+    {
+      if (w_sensors == "")
+        w_sensors=sensor_name[NR]" = "sensor_status[NR]
+      else
+        w_sensors=w_sensors", "sensor_name[NR]" = "sensor_status[NR]
+    }
+  }
 
-	if (sensor_units[NR] != "N/A")
-	{
-		number_of_numerical_records++
-		n_record_name[number_of_numerical_records]=sensor_name[NR]
-		n_record_value[number_of_numerical_records]=sensor_reading[NR]
-	}
+  if (sensor_units[NR] != "N/A")
+  {
+    number_of_numerical_records++
+    n_record_name[number_of_numerical_records]=sensor_name[NR]
+    n_record_value[number_of_numerical_records]=sensor_reading[NR]
+  }
 }
 
 ################################################################################
@@ -356,61 +356,61 @@ $4 !~ /Monitoring Status/ {
 #   see http://www.gnu.org/software/gawk/manual/html_node/Using-BEGIN_002fEND.html
 # * we print the data which has been collected above in this part below
 END {
-	########################################################################
-	# * build perfdata string (variable pstring) using quotes
-	#   see http://www.gnu.org/software/gawk/manual/html_node/Quoting.html
-	while(j<number_of_numerical_records) {
-		j++
-		if (outformat == "zenoss")
-			pstring=pstring""n_record_name[j]"="n_record_value[j]" "
-		else
-			pstring=pstring"\47"n_record_name[j]"\47="n_record_value[j]" "
-	}
+  ########################################################################
+  # * build perfdata string (variable pstring) using quotes
+  #   see http://www.gnu.org/software/gawk/manual/html_node/Quoting.html
+  while(j<number_of_numerical_records) {
+    j++
+    if (outformat == "zenoss")
+      pstring=pstring""n_record_name[j]"="n_record_value[j]" "
+    else
+      pstring=pstring"\47"n_record_name[j]"\47="n_record_value[j]" "
+  }
 
-	########################################################################
-	# * print status message (first text output line)
-	if (EXIT==0)
-	{
-		if (number_of_numerical_records>0)
-			print "OK | "pstring
-		else
-			print "OK"
-	}
-	else
-	{
-		if (EXIT==1)
-		{
-			if (number_of_numerical_records>0)
-				print "Warning ["w_sensors"] | "pstring
-			else
-				print "Warning ["w_sensors"]"
-		}
-		else
-		{
-			if (number_of_numerical_records>0)
-				print "Critical ["w_sensors"] | "pstring
-			else
-				print "Critical ["w_sensors"]"
-		}
-	}
+  ########################################################################
+  # * print status message (first text output line)
+  if (EXIT==0)
+  {
+    if (number_of_numerical_records>0)
+      print "OK | "pstring
+    else
+      print "OK"
+  }
+  else
+  {
+    if (EXIT==1)
+    {
+      if (number_of_numerical_records>0)
+        print "Warning ["w_sensors"] | "pstring
+      else
+        print "Warning ["w_sensors"]"
+    }
+    else
+    {
+      if (number_of_numerical_records>0)
+        print "Critical ["w_sensors"] | "pstring
+      else
+        print "Critical ["w_sensors"]"
+    }
+  }
 
-	########################################################################
-	# * print additional text lines (multi-line output) for verbosity > 1
-	if (verbosity>1)
-	{
-		while(i<FNR)
-		{
-			i++
-			exclude="false"
-		        for (counter in xl_array)
-                		if (sensor_id[i] == xl_array[counter]) exclude="true"
-			########################################################
-			# "i > 1" is necessary to omit the header output line
-			if (i > 1 && exclude == "false")
-				print sensor_name[i],"=",sensor_reading[i],"(Status:",sensor_status[i]")"
-		}
-	}
-	exit EXIT
+  ########################################################################
+  # * print additional text lines (multi-line output) for verbosity > 1
+  if (verbosity>1)
+  {
+    while(i<FNR)
+    {
+      i++
+      exclude="false"
+            for (counter in xl_array)
+                    if (sensor_id[i] == xl_array[counter]) exclude="true"
+      ########################################################
+      # "i > 1" is necessary to omit the header output line
+      if (i > 1 && exclude == "false")
+        print sensor_name[i],"=",sensor_reading[i],"(Status:",sensor_status[i]")"
+    }
+  }
+  exit EXIT
 }
 '
 fi
